@startuml components

!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Ext(apigw, "API Gateway", "Spring Gateway", "Маршрутизация запросов и аутетификация")

Container_Boundary(telemetryservice, "Telemetry Service"){
    Component(controller, "RestController", "Spring REST Controller", "API endpoint для передачи данных телеметрии")
    Component(handler, "EventHandler", "Kafka Consumer", "Обработка событий телеметрии")
    Component(dbwriter, "InfluxDBWriter", "Spring Bean", "description")
}

ContainerDb_Ext(telemetrydb, "Telemetry DB", "InfluxDB", "Хранение телеметрии с IoT-устройств")
Container_Ext(kafka, "Kafka", "Kafka", "Шина событий")

Rel(apigw, controller, "Вызов API (Маршрутизация запросов пользователя)", "HTTP")
Rel(kafka, handler, "Доставка телеметрии", "Consumer")
Rel(controller, dbwriter, "")
Rel(handler, dbwriter, "")
Rel(dbwriter, telemetrydb, "Чтение/запись", "HTTP / InfluxDB Line Protocol")

@enduml 