@startuml context
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(client, "Пользователь", "Клиент компании, установивший IoT-устройства, интегрированные с нашей системой")
Person(specialist, "Специалист", "Сотрудник компании, который администрирует подключение и вывод IoT-устройств")
System(warmhouse, "Тёплый дом", "Система, которая предоставляет, объединяет, управляет и анализирует данные от распределённых IoT-устройств")
System_Ext(device, "IoT-Устройство", "Устройство, которое может выполнять команды и/или измерять параметры окружающей среды")

Rel(client, warmhouse, "Просмотр данных с датчиков и удаленное управление устройствами", "Веб-интерфейс")
Rel(specialist, warmhouse, "Администрирование устройств и датчиков в системе (добавление, удаление)", "Веб-интерфейс")
Rel(warmhouse, device, "Получение данных и выполнение команд", "API")

@enduml 